### 晨测
- 谈一谈 promise
    什么是Promise:
        - 回调函数嵌套回调函数被称作回调地狱，代码层层嵌套，环环相扣，很明显，逻辑稍微复杂一些，这样的程序就会变得难以维护。代码臃肿，可读性差，耦合度过高
        - ES2015的标准里，Promise的标准化，一定程度上解决了JavaScript的流程操作问题。Promise对象是一个异步编程的解决方案，可以将异步操作以同步的流程表达出来, 避免了层层嵌套的回调函数(俗称'回调地狱')

    Promise的使用
        - Promise是一个构造函数，接受一个参数是一个回调函数
        - Promise是解决回调地狱的问题，也就是解决异步的问题，但是Promise自身并不是异步的
        - Promise实例化时传递的回调函数，接受两个参数，一个是resolve，一个是reject


    Promise的实例化对象:
        - PromiseState属性：当前Promise实例化对象的状态
        - PromiseResult属性：当前Promise实例化对象的值

    Promise实例化对象的状态：
        - pending:正在执行异步代码，默认就是pending状态
        - fulfilled:当前Promise对象内的异步代码执行成功（在Promise的回调函数中调用了resolve方法）
        - rejected:当前Promise对象内的异步代码执行失败（在promise的回调函数中调用了reject方法）
        - 注意:promise对象的状态只能从pending转为其他状态

- then的返回值
    Promise的原型对象方法：then、catch、finally

    then方法：
        - then方法是异步的，是实例化的promise对象调用，当实例化的promise对象不再是pending状态的时候，会调用then方法
        - 因为then是解决异步嵌套的核心流程，所以then方法一定返回的是promise对象

    then的返回值：
        - 成功的promise对象调用then方法
            - then中一般接受一个回调函数作为参数，回调函数内部用来处理下一步操作
                - 默认then返回的是一个成功的promise对象,promise对象的值就是当前回调函数的返回值
                - 当then中返回的是一个promise对象的时候，then返回的promise对象的状态和值就是回调函数返回的promise对象的状态和值
                - 当then的回调函数内部出现报错并且没有异常处理，则直接then返回失败的promise对象，值为这个错误
            - then中值传递一个值，会直接发生值穿透，then返回成功状态的promise对象，值是调用then的namepromise对象的值

        -  失败的promise对象调用then方法
            - then直接返回一个失败的promise对象，并且值是调用then的那个失败的promise对象的值

- catch的返回值
    - 失败的promise对象调用catch方法
        - 当catch中没有书写回调函数的时候，会发生值穿透，直接返回失败的，值为调用catch的失败的promise对象的值
        - 当catch中书写了回调函数，则catch的返回值规则和then一样（默认成功，catch中报错、返回失败的promise对象这两种情况才会返回失败）
        

    -  成功的promise对象调用catch方法
        - catch直接返回一个成功的promise对象，并且值是调用catch的那个成功的promise对象的值

-  finally的返回值
    - 总结：
        - 当finally中的回调函数返回的是失败的promise对象的时候，则finally返回失败状态的promis对象，值为回调函数返回promise对象的值
        - 当finally的回调函数中出现报错，则finally直接返回失败的promise对象，值为错误信息
        - 其他情况一律认为类似穿透